/* ZERO TO EMPIRE — PHASE 9: POLISH, LOCAL ANALYTICS & SHIP CHECKS */
(()=>{
  const VERSION='phase9-v1';
  function ensure(){
    st.phase9={version:VERSION,startedAt:Date.now(),startingWorth:0,history:[],biggestPayout:0,hustles:0,sessions:1,tutorialSeen:false,lastRecapDay:st.day||1,lastRecapWorth:0,...st.phase9};
    st.phase9.history=Array.isArray(st.phase9.history)?st.phase9.history:[];
    if(!Number.isFinite(st.cash))st.cash=0;if(!Number.isFinite(st.energy))st.energy=100;if(!Number.isFinite(st.day))st.day=1;
    st.energy=Math.max(0,Math.min(100,st.energy));
    if(!st.biz)st.biz={};if(!st.property)st.property={owned:false,financed:false,debt:0,value:6000,rentBoost:0};
    if(!st.upgrades)st.upgrades=[];if(!st.lifestyle)st.lifestyle=[];if(!st.skills)st.skills={negotiation:0,management:0,marketing:0};
  }
  ensure();
  function snap(){ensure();const w=Math.max(0,netWorth());const last=st.phase9.history[st.phase9.history.length-1];if(!last||last.day!==st.day){st.phase9.history.push({day:st.day,worth:w,cash:st.cash});if(st.phase9.history.length>120)st.phase9.history.shift()}else{last.worth=w;last.cash=st.cash}}
  const saveBase=save;save=function(){ensure();snap();saveBase()};

  const style=document.createElement('style');style.textContent='.metricGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metric{border:1px solid #343a35;background:#0a0e0c;border-radius:13px;padding:11px}.metric b{display:block;color:var(--g2);font-size:18px}.spark{height:90px;display:flex;align-items:flex-end;gap:3px;border-bottom:1px solid #343a35;padding:8px 0}.spark i{display:block;flex:1;min-width:2px;background:linear-gradient(#ffd978,#a87917);border-radius:3px 3px 0 0}.tutorialShade{position:absolute;inset:0;background:#000c;z-index:90;display:flex;align-items:flex-end;padding:24px}.tutorialCard{width:100%;background:#121713;border:1px solid #b18c32;border-radius:22px;padding:18px;box-shadow:0 0 40px #e7ba4730}.shipOk{color:#52df73}.shipWarn{color:#ffd978}';document.head.appendChild(style);

  const sec=document.createElement('section');sec.id='stats';sec.className='s';sec.innerHTML='<div class="top"><button class="back" data-go="world">‹</button><div class="ttl">YOUR EMPIRE</div><div style="width:44px"></div></div><div class="panel"><h3>LOCAL EMPIRE STATS</h3><div id="p9Metrics" class="metricGrid"></div><div id="p9Spark" class="spark"></div></div><div class="panel"><h3>PROGRESS RECAP</h3><div id="p9Recap"></div></div><div class="panel"><h3>SAVE & SHIP HEALTH</h3><div class="sub">Local diagnostics for backward-compatible state and reachable progression.</div><div id="p9Checks"></div></div><div class="panel"><h3>FUTURE SOCIAL HOOK</h3><div class="sub">Local stats use a stable summary object so a future backend leaderboard/friend comparison can upload the same metrics without replacing this screen.</div><div class="stub">BACKEND HOOK PLACEHOLDER: syncEmpireSummary(summary) — intentionally not connected.</div></div><button class="btn dk sm" data-go="world">BACK</button>';
  document.getElementById('app').appendChild(sec);sec.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
  let entry=document.createElement('div');entry.className='panel';entry.id='phase9Panel';entry.innerHTML='<h3>YOUR EMPIRE</h3><div class="sub">Progress history, session recaps and local ship diagnostics.</div><button id="openStats" class="btn sm">OPEN EMPIRE STATS</button>';document.getElementById('sleepBtn')?.parentNode?.insertBefore(entry,document.getElementById('sleepBtn'));$('openStats').onclick=()=>show('stats');

  function ownedCount(){let n=['detail','fleet','third'].filter(k=>st.biz?.[k]?.owned).length;n+=Object.values(st.extraBiz||{}).filter(x=>x?.owned).length;n+=Object.values(st.phase7?.empireBiz||{}).filter(x=>x?.owned).length;return n}
  function summary(){return{netWorth:Math.round(netWorth()),cash:Math.round(st.cash),businesses:ownedCount(),days:st.day,biggestPayout:st.phase9.biggestPayout,hustles:st.phase9.hustles,character:st.character,passivePerDay:Math.round(passiveFlow())}}
  window.syncEmpireSummary=function(summary){console.info('[FUTURE SOCIAL STUB] backend leaderboard not connected',summary)};
  function checks(){const a=[];a.push(['Save state readable',!!st&&Number.isFinite(st.cash)]);a.push(['Energy bounded 0–100',st.energy>=0&&st.energy<=100]);a.push(['Net worth valid',Number.isFinite(netWorth())&&netWorth()>=0]);a.push(['Phase 6 migration',!!st.phase6]);a.push(['Phase 7 migration',!!st.phase7]);a.push(['Phase 8 migration',!!st.phase8]);a.push(['Phase 9 migration',!!st.phase9]);a.push(['Core hustle available',!!document.getElementById('washBtn')]);a.push(['Character portraits wired',document.querySelectorAll('#cards img').length===8]);return a}
  function render(){ensure();snap();const s=summary();$('p9Metrics').innerHTML='<div class="metric"><span class="sub">NET WORTH</span><b>'+fmt(s.netWorth)+'</b></div><div class="metric"><span class="sub">PASSIVE / DAY</span><b>'+fmt(s.passivePerDay)+'</b></div><div class="metric"><span class="sub">BUSINESSES</span><b>'+s.businesses+'</b></div><div class="metric"><span class="sub">DAYS PLAYED</span><b>'+s.days+'</b></div><div class="metric"><span class="sub">BIGGEST PAYOUT</span><b>'+fmt(s.biggestPayout)+'</b></div><div class="metric"><span class="sub">HUSTLES</span><b>'+s.hustles+'</b></div>';
    let h=st.phase9.history.slice(-24),max=Math.max(1,...h.map(x=>x.worth));$('p9Spark').innerHTML=h.map(x=>'<i title="Day '+x.day+' • '+fmt(x.worth)+'" style="height:'+Math.max(3,Math.round(x.worth/max*80))+'px"></i>').join('');
    const gain=s.netWorth-(st.phase9.lastRecapWorth||0);$('p9Recap').innerHTML='<div class="biz phaseDone"><b class="gold">DAY '+st.day+' RECAP</b><div class="sub">Current empire '+fmt(s.netWorth)+' • '+(gain>=0?'+':'')+fmt(gain)+' since last recap checkpoint • '+s.businesses+' businesses • '+fmt(s.passivePerDay)+'/day passive.</div><button id="checkpoint" class="btn sm">SET RECAP CHECKPOINT</button></div>';$('checkpoint').onclick=()=>{st.phase9.lastRecapWorth=s.netWorth;st.phase9.lastRecapDay=st.day;save();render()};
    $('p9Checks').innerHTML=checks().map(([n,ok])=>'<div class="sub '+(ok?'shipOk':'shipWarn')+'" style="margin-top:6px">'+(ok?'✓':'⚠')+' '+n+'</div>').join('')+'<div class="sub" style="margin-top:10px">Ship target: continuous $0 → $10M playthrough, no forced ads, no fake transactions, no hard game-over.</div>';
  }

  function tutorial(){ensure();if(st.phase9.tutorialSeen)return;const sh=document.createElement('div');sh.className='tutorialShade';sh.innerHTML='<div class="tutorialCard"><div class="sub gold" style="font-weight:900;letter-spacing:.12em">FIRST HUSTLE</div><h2 style="margin:5px 0">START WITH WHAT YOU HAVE.</h2><p class="sub" style="font-size:12px;line-height:1.5">Wash your first car by swiping over the dirt spots. Finish once it is at least 35% clean. Cleaner work earns better tips. Every job costs energy.</p><button class="btn" id="tutorialGo">GOT IT • START HUSTLING</button></div>';document.getElementById('app').appendChild(sh);$('tutorialGo').onclick=()=>{st.phase9.tutorialSeen=true;save();sh.remove()}}
  function notePayout(before){const delta=Math.max(0,st.cash-before);if(delta>st.phase9.biggestPayout)st.phase9.biggestPayout=delta}
  document.getElementById('deliveryCollect')?.addEventListener('click',()=>{st.phase9.hustles++;save()});document.getElementById('collect')?.addEventListener('click',()=>{st.phase9.hustles++;save()});
  document.getElementById('sleepBtn')?.addEventListener('pointerdown',()=>{st.phase9._beforeSleep=st.cash});document.getElementById('sleepBtn')?.addEventListener('click',()=>{setTimeout(()=>{notePayout(st.phase9._beforeSleep||st.cash);save()},20)});
  const showBase=show;show=function(x){showBase(x);if(x==='world')setTimeout(tutorial,120);if(x==='stats')render()};
  const hudBase=hud;hud=function(){ensure();hudBase();if(document.getElementById('stats')?.classList.contains('on'))render()};
  snap();saveBase();render();
})();